name: nextjs-博客项目

on:
    push:  # 当main分支被push，以及paths里面定义的被改变时，触发xxx命令
        branches: 
            - 'master' #push操作时，对应的分支
        paths: 
            - '.github/workflows/*' #  什么文件或者文件夹里的文件变动时，触发
            - 'src/*'
            - 'package.json'
            - 'utils/*'
            - '.gitignore'
            - 'next.config.mjs'
            - 'postcss.config.mjs'
            - 'tailwind.config.mjs'
            - 'jsconfig.json'
            - '.env.production'
            
jobs: 

    deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 15

        steps:
            - uses: actions/checkout@v4 #使用哪一个已经好了的action，除了这个action之外，还有其他功能的action

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.8.0
              with:
                ssh-private-key: ${{ secrets.ALIYUN_ESC_SECRET }}

            - name: Deploy with Docker
              run: |
                ssh -o StrictHostKeyChecking=no root@8.134.205.132 '
                  cd /project/blogs/nextjs-blog-demo &&
                  git pull &&
                  docker build -t nextjs-blog . &&
                  docker stop nextjs-blog-container || true &&
                  docker rm nextjs-blog-container || true &&
                  docker run -d \
                    --name nextjs-blog-container \
                    -p 3000:3000 \
                    -e NODE_ENV=production \
                    --restart unless-stopped \
                    nextjs-blog
                '

