name: nextjs-博客项目

on:
    push:  # 当main分支被push，以及paths里面定义的被改变时，触发xxx命令
        branches: 
            - 'master' #push操作时，对应的分支
        paths: 
            - '.github/workflows/*' #  什么文件或者文件夹里的文件变动时，触发
            - 'src/*'
            - 'package.json'
            - 'utils/*'
            - '.gitignore'
            - 'next.config.mjs'
            - 'postcss.config.mjs'
            - 'tailwind.config.mjs'
            - 'jsconfig.json'
            - '.env.production'
            - 'Dockerfile'
            
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4 # --使用哪一个已经好了的action，除了这个action之外，还有其他功能的action

      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      # 安装依赖并构建
      - name: Install dependencies and build
        run: |
          echo "安装依赖..."
          npm ci --no-audit --no-fund
          echo "构建应用..."
          npm run build:prod
          echo "检查构建输出..."
          ls -la .next/static/css/
          cat .next/static/css/*.css | wc -l
          
      # 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t nextjs-blog .
          docker save nextjs-blog > nextjs-blog.tar
          
      # 设置 SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.ALIYUN_ESC_SECRET }}
          
      # 将 Docker 镜像传输到服务器并部署
      - name: Deploy to server
        run: |
          # 将 Docker 镜像传输到服务器
          scp -o StrictHostKeyChecking=no nextjs-blog.tar root@8.134.205.132:/tmp/
          
          # 在服务器上加载镜像并运行容器
          ssh -o StrictHostKeyChecking=no root@8.134.205.132 '
            cd /project/blogs/nextjs-blog-demo &&
            docker load < /tmp/nextjs-blog.tar &&
            docker stop nextjs-blog-container || true &&
            docker rm nextjs-blog-container || true &&
            docker run -d \
              --name nextjs-blog-container \
              -p 9528:8866 \
              -e NODE_ENV=production \
              -e NEXT_PUBLIC_HOST=http://8.134.205.132:6677 \
              --restart unless-stopped \
              nextjs-blog:latest &&
            rm /tmp/nextjs-blog.tar
          '

